version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.15
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run:
          name: Update application
          command: npm update
      - run:
          name: run tests
          command: npm test
